Vagrant.configure("2") do |config|
   config.vm.box = "kors89/centos7"
   config.vm.hostname = "single"
   config.vm.provider "virtualbox" do |v|
	 v.customize ["modifyvm", :id, "--usb", "on"]
     v.customize ["modifyvm", :id, "--usbehci", "off"]
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "75", "--memory", "1024", "--cpus", "1", "--name", "single"]
   end
   
   config.vm.network "forwarded_port", guest: 80, host: 8080
   
   config.vm.synced_folder "vagrant_share/", "/custom_shared"

   config.vm.provision "shell", path: "script.sh"
   config.vm.provision "file", source: "index.php", destination: "/var/www/html/index.php"

end
